[package]
name = "move0-methods"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]
